version: '3.7'

services:
  db:
    image: postgres:9.5.4
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: luigi
      POSTGRES_DB: dev
    networks:
    - pipeline
    - api

  scheduler:
    build:
      dockerfile: scheduler/Dockerfile
      context: .
    ports:
      - "8082:8082"
    environment:
      LUIGI_TASK_HISTORY_DB_CONNECTION: postgres://luigi@db/dev
      LUIGI_SCHEDULER_RECORD_TASK_HISTORY: "true"
    entrypoint:
      - ./wait-for-postgres.sh
      - db
    networks:
      - pipeline

  worker:
    build:
      dockerfile: worker/Dockerfile
      context: .
    hostname: worker
    volumes:
      - .:/luigi
    environment:
      LUIGI_CORE_DEFAULT-SCHEDULER-URL: http://scheduler:8082
    depends_on:
      - scheduler
    networks:
      - pipeline


networks:
  pipeline:
  api:
